#Download base image nginx with latest version
FROM nginx:latest

#Copy contents of particular directory on host machine to the particular directory in nginx container
COPY /docker-nginx/html /usr/share/nginx/html
